"""Contract-governed dal-mufrad pipeline.

This package models lexical sign closure only (الدال المفرد),
without semantic meaning inference.
"""

from .pipeline import (
    Rank,
    Severity,
    Evidence,
    Residual,
    LexicalType,
    LexiconRecord,
    DForm,
    DLugha,
    DType,
    DMufrad,
    SEED_LEXICON,
    analyze_dal_mufrad,
    build_d_form,
    prove_lugha,
    infer_type,
    close_mufrad,
    atoms_from_text,
    attach_marks,
)

from .mufrad_proof import MufradProof
from .morph_features import (
    CandidateStatus,
    SegmentationProof,
    StemProof,
    CliticProof,
    RootCandidate,
    WaznCandidate,
    VerbFeatureProof,
    NounInflectionClass,
    ParticleOperatorPotential,
)
from .surface_effects import (
    SurfaceEffect,
    SurfaceEffectType,
    SurfaceEffectVisibility,
)
from .composition_readiness import CompositionReadiness
from .operator_contract import OperatorContract
from .case_signs import (
    CaseSignFamily,
    CaseSignValue,
    CaseSignPotential,
    CaseSignResidualType,
)
from .type_ids import (
    NounTypeID,
    VerbTypeID,
    ParticleTypeID,
    CompositeTypeID,
)
from .presyntax_vector import PreSyntaxMufradVector
from .sentence_frame import (
    FrameType,
    SentenceFrameCandidate,
    NominalFrameCandidate,
    VerbalFrameCandidate,
    ParticleLedFrameCandidate,
    FragmentFrameCandidate,
    UnresolvedFrameCandidate,
    calculate_frame_rank,
    collect_inherited_residuals,
)
from .frame_builder import (
    FrameBuilder,
    build_sentence_frames,
)
from .case_sign_matrix import (
    CaseCompatibilityFamily,
    SurfaceSignObservation,
    CaseSignMatrixRow,
    CaseSignMatrixTrace,
    CaseSignMatrix,
    CaseSignMatrixBuilder,
    build_case_sign_matrix,
)
from .operator_trigger import (
    OperatorTriggerFamily,
    TriggerSource,
    OperatorTriggerTrace,
    OperatorTriggerPotential,
    OperatorTriggerPotentialBuilder,
    build_operator_trigger_potential,
)
from .nahw_operator_registry import (
    OperatorSource,
    NahwSchool,
    ExpectedRelationFamily,
    CaseEffectPolicyFamily,
    ActivationCondition,
    BlockingCondition,
    OperatorInputSignature,
    Citation,
    NahwOperatorEntry,
    OperatorRegistryLookupResult,
    NahwOperatorRegistry,
    build_default_nahw_operator_registry,
)
from .operator_candidate import (
    OperatorCandidateTrace,
    OperatorCandidate,
    OperatorCandidateSet,
    build_operator_candidates,
)
from .dal_algebra import (
    DalTransitionDomain,
    DalClaimScope,
    EvidenceRequirement,
    ShortcutPolicy,
    CandidateBudgetPolicy,
    DalEvidence,
    DalCounterEvidence,
    DalTraceRef,
    DalTransitionContract,
    DalCandidateProtocol,
    DalCandidateSetProtocol,
    DalTransitionProtocol,
    validate_transition_contract,
    validate_candidate_set_shape,
    ensure_no_forbidden_outputs,
    validate_no_direct_promotion,
    FORBIDDEN_AXIS_PROMOTIONS,
    assert_axis_promotion_allowed,
)
from .mufrad_axes import (
    BinaaJudgment,
    BinaaSubtype,
    IshtiqaqJudgment,
    MushtaqSubtype,
    JamidSubtype,
    SarfFlexibility,
)
from .mabni_registry import (
    MabniCategory,
    MabniEntry,
    MabniRegistry,
    get_default_mabni_registry,
)
from .binaa_judge import (
    BinaaJudgeInput,
    BinaaJudgmentResult,
    judge_binaa,
)
from .ishtiqaq_judge import (
    IshtiqaqJudgeInput,
    IshtiqaqJudgmentResult,
    judge_ishtiqaq,
)
from .syllable_candidate import (
    SyllableCandidate,
    SyllableCandidateSet,
    detect_syllable_boundaries,
    generate_syllable_candidate,
    generate_syllable_candidates,
    syllabify_word,
)
from .d1_correctness import (
    CorrectnessCheck,
    Corr_D1_Result,
    validate_corr_d1,
    verify_source_atoms_preserved,
    verify_atom_order_preserved,
    verify_no_atom_loss,
    verify_span_correct,
    verify_syllable_pattern_legal,
    verify_nucleus_valid,
    verify_trace_exists,
    verify_no_cross_layer_leakage,
    verify_trace_actually_reversible,
    reverse_syllable_candidate,
)
from .d1_failures import (
    D1FailureType,
    D1Failure,
    D1FailureSet,
    make_empty_sequence_failure,
    make_missing_nucleus_failure,
    make_missing_onset_failure,
    make_illegal_pattern_failure,
    make_boundary_ambiguity_failure,
    make_long_vowel_ambiguity_failure,
    make_shadda_expansion_failure,
    make_sukun_conflict_failure,
    make_trace_loss_failure,
    make_atom_loss_failure,
    make_atom_order_violation_failure,
    make_span_mismatch_failure,
    make_non_reversible_trace_failure,
    make_candidate_overflow_failure,
    suggest_recovery,
    is_recoverable,
)
from .d1_rank_policy import (
    SyllableRankVector,
    DEFAULT_RANK_WEIGHTS,
    compute_pattern_legality,
    compute_boundary_confidence,
    compute_trace_completeness,
    compute_atom_coverage,
    compute_ambiguity_penalty,
    compute_long_vowel_confidence,
    compute_shadda_sukun_handling,
    compute_syllable_rank,
    rank_candidates,
    best_candidate_by_rank,
    rank_is_not_certificate,
    confidence_is_not_certificate,
)
from .algebraic_decision_core import (
    CPBStatus,
    DecisionAudit,
    CPBIdentityGuardian,
    AlgebraicDecisionCore,
)
from .identity_registry import (
    IdentityType,
    IdentityLayer,
    IdentitySpec,
    IdentityRegistry,
    verify_identity_preserved,
)
from .domain_registry import (
    DomainType,
    DomainLayer,
    DomainSpec,
    DomainRegistry,
    verify_domain_boundary,
)

__all__ = [
    "Rank",
    "Severity",
    "Evidence",
    "Residual",
    "LexicalType",
    "LexiconRecord",
    "DForm",
    "DLugha",
    "DType",
    "DMufrad",
    "SEED_LEXICON",
    "analyze_dal_mufrad",
    "build_d_form",
    "prove_lugha",
    "infer_type",
    "close_mufrad",
    "atoms_from_text",
    "attach_marks",
    # MufradProof and supporting types
    "MufradProof",
    "CandidateStatus",
    "SegmentationProof",
    "StemProof",
    "CliticProof",
    "RootCandidate",
    "WaznCandidate",
    "VerbFeatureProof",
    "NounInflectionClass",
    "ParticleOperatorPotential",
    "SurfaceEffect",
    "SurfaceEffectType",
    "SurfaceEffectVisibility",
    "CompositionReadiness",
    "OperatorContract",
    # Case signs and type IDs
    "CaseSignFamily",
    "CaseSignValue",
    "CaseSignPotential",
    "CaseSignResidualType",
    "NounTypeID",
    "VerbTypeID",
    "ParticleTypeID",
    "CompositeTypeID",
    "PreSyntaxMufradVector",
    # Sentence frames
    "FrameType",
    "SentenceFrameCandidate",
    "NominalFrameCandidate",
    "VerbalFrameCandidate",
    "ParticleLedFrameCandidate",
    "FragmentFrameCandidate",
    "UnresolvedFrameCandidate",
    "calculate_frame_rank",
    "collect_inherited_residuals",
    "FrameBuilder",
    "build_sentence_frames",
    # CaseSignMatrix (PR #13)
    "CaseCompatibilityFamily",
    "SurfaceSignObservation",
    "CaseSignMatrixRow",
    "CaseSignMatrixTrace",
    "CaseSignMatrix",
    "CaseSignMatrixBuilder",
    "build_case_sign_matrix",
    # OperatorTriggerPotential (PR #14)
    "OperatorTriggerFamily",
    "TriggerSource",
    "OperatorTriggerTrace",
    "OperatorTriggerPotential",
    "OperatorTriggerPotentialBuilder",
    "build_operator_trigger_potential",
    # NahwOperatorRegistry (PR #15)
    "OperatorSource",
    "NahwSchool",
    "ExpectedRelationFamily",
    "CaseEffectPolicyFamily",
    "ActivationCondition",
    "BlockingCondition",
    "OperatorInputSignature",
    "Citation",
    "NahwOperatorEntry",
    "OperatorRegistryLookupResult",
    "NahwOperatorRegistry",
    "build_default_nahw_operator_registry",
    # OperatorCandidate (PR #17)
    "OperatorCandidateTrace",
    "OperatorCandidate",
    "OperatorCandidateSet",
    "build_operator_candidates",
    # DalAlgebra (PR #23 - Minimal Dal Transition Signature)
    "DalTransitionDomain",
    "DalClaimScope",
    "EvidenceRequirement",
    "ShortcutPolicy",
    "CandidateBudgetPolicy",
    "DalEvidence",
    "DalCounterEvidence",
    "DalTraceRef",
    "DalTransitionContract",
    "DalCandidateProtocol",
    "DalCandidateSetProtocol",
    "DalTransitionProtocol",
    "validate_transition_contract",
    "validate_candidate_set_shape",
    "ensure_no_forbidden_outputs",
    "validate_no_direct_promotion",
    "FORBIDDEN_AXIS_PROMOTIONS",
    "assert_axis_promotion_allowed",
    # Mufrad axes (PR-A through PR-D)
    "BinaaJudgment",
    "BinaaSubtype",
    "IshtiqaqJudgment",
    "MushtaqSubtype",
    "JamidSubtype",
    "SarfFlexibility",
    "MabniCategory",
    "MabniEntry",
    "MabniRegistry",
    "get_default_mabni_registry",
    "BinaaJudgeInput",
    "BinaaJudgmentResult",
    "judge_binaa",
    "IshtiqaqJudgeInput",
    "IshtiqaqJudgmentResult",
    "judge_ishtiqaq",
    # Syllable Candidate Layer (PR #30)
    "SyllableCandidate",
    "SyllableCandidateSet",
    "detect_syllable_boundaries",
    "generate_syllable_candidate",
    "generate_syllable_candidates",
    "syllabify_word",
    # AlgebraicDecisionCore (Governance Layer)
    "CPBStatus",
    "DecisionAudit",
    "CPBIdentityGuardian",
    "AlgebraicDecisionCore",
    "IdentityType",
    "IdentityLayer",
    "IdentitySpec",
    "IdentityRegistry",
    "verify_identity_preserved",
    "DomainType",
    "DomainLayer",
    "DomainSpec",
    "DomainRegistry",
    "verify_domain_boundary",
]
