"""
Model Output Contract (عقد مخرجات النموذج)

PR #147: Constitutional evaluation harness for model outputs.

Constitutional Laws:
    1. ModelOutput is immutable serialization container
    2. ModelOutput MUST preserve source_training_example_id
    3. ModelOutput MUST preserve source_trace_id
    4. ModelOutput does NOT create candidates
    5. ModelOutput does NOT upgrade rank
    6. ModelOutput does NOT delete residuals
    7. ModelOutput does NOT close ifādah
    8. ModelOutput does NOT produce hukm
    9. ModelOutput does NOT produce reality
    10. ModelOutput is evaluation input, NOT authority

Forbidden Pipeline:
    ❌ Raw Arabic → ModelOutput
    ❌ ModelOutput → Candidate
    ❌ ModelOutput → Rank Upgrade
    ❌ ModelOutput → Residual Resolution
    ❌ ModelOutput → Ifādah Closure
    ❌ ModelOutput → Hukm
    ❌ ModelOutput → Reality

Permitted Pipeline:
    ✅ TrainingExample + Model Prediction → ModelOutput
    ✅ ModelOutput + TrainingExample → ConstitutionalViolationReport

Constitutional Formula:
    ModelOutput = predicted text + constitutional source bindings
    ConstitutionalEvaluator = guardian detecting violations
    T5 learns to explain traces, NOT to produce authority

Supreme Law:
    Model outputs are predictions subject to constitutional review.
    Model outputs do NOT create constitutional facts.

Reference:
    User requirement: PR #147 specification (2026-05-29)
    Builds on: PR #141, PR #142, PR #145, PR #146

Created: 2026-05-29
"""

from dataclasses import dataclass
from datetime import datetime


# ============================================================================
# Model Output
# ============================================================================

@dataclass(frozen=True)
class ModelOutput:
    """
    Single immutable model output for constitutional evaluation.

    Constitutional Requirements:
        - All fields are immutable (frozen=True)
        - model_output_id is unique identifier
        - source_training_example_id MUST reference valid TrainingExample
        - source_trace_id MUST reference valid AlgorithmTracePayload
        - predicted_text is model's generated output (subject to review)
        - model_name preserves model identification
        - generation_timestamp preserves when prediction was made

    Forbidden Fields:
        ❌ upgraded_rank: ModelOutput does NOT upgrade rank
        ❌ resolved_residuals: ModelOutput does NOT resolve residuals
        ❌ closed_ifadah: ModelOutput does NOT close ifādah
        ❌ produced_hukm: ModelOutput does NOT produce hukm
        ❌ produced_reality: ModelOutput does NOT produce reality
        ❌ new_candidate: ModelOutput does NOT create candidates
        ❌ semantic_certainty: ModelOutput does NOT produce semantic certainty
        ❌ final_answer: ModelOutput does NOT assert final answers
        ❌ correct_analysis: ModelOutput does NOT assert correct analysis
        ❌ constitutional_authority: ModelOutput does NOT have authority

    Fields:
        model_output_id: Unique identifier for this model output
        source_training_example_id: training_example_id from TrainingExample (CONSTITUTIONAL BINDING)
        source_trace_id: trace_id from AlgorithmTracePayload (CONSTITUTIONAL BINDING)
        predicted_text: Text generated by model (subject to constitutional review)
        model_name: Name/identifier of model that generated output
        generation_timestamp: When prediction was generated (ISO 8601 format)
    """
    model_output_id: str
    source_training_example_id: str
    source_trace_id: str
    predicted_text: str
    model_name: str
    generation_timestamp: str  # ISO 8601 format

    def __post_init__(self):
        """
        Validate ModelOutput constitutional requirements.

        Raises:
            ValueError: If constitutional requirements are violated
        """
        # Validate required fields
        if not self.model_output_id:
            raise ValueError("ModelOutput requires model_output_id")

        if not self.source_training_example_id:
            raise ValueError(
                "Constitutional violation: ModelOutput MUST preserve source_training_example_id"
            )

        if not self.source_trace_id:
            raise ValueError(
                "Constitutional violation: ModelOutput MUST preserve source_trace_id"
            )

        if not self.predicted_text:
            raise ValueError("ModelOutput requires predicted_text")

        if not self.model_name:
            raise ValueError("ModelOutput requires model_name")

        if not self.generation_timestamp:
            raise ValueError("ModelOutput requires generation_timestamp")

    @staticmethod
    def create_from_prediction(
        source_training_example_id: str,
        source_trace_id: str,
        predicted_text: str,
        model_name: str,
    ) -> "ModelOutput":
        """
        Create ModelOutput from model prediction.

        Constitutional Requirements:
            1. source_training_example_id MUST be preserved
            2. source_trace_id MUST be preserved
            3. All source bindings MUST be maintained

        Args:
            source_training_example_id: ID from TrainingExample
            source_trace_id: ID from AlgorithmTracePayload
            predicted_text: Model's generated text
            model_name: Name/identifier of model

        Returns:
            ModelOutput with all constitutional bindings preserved

        Raises:
            ValueError: If required bindings are missing
        """
        from uuid import uuid4

        model_output_id = f"model_output_{uuid4().hex[:16]}"
        generation_timestamp = datetime.utcnow().isoformat() + "Z"

        return ModelOutput(
            model_output_id=model_output_id,
            source_training_example_id=source_training_example_id,
            source_trace_id=source_trace_id,
            predicted_text=predicted_text,
            model_name=model_name,
            generation_timestamp=generation_timestamp,
        )
