"""
RealityGeometry Kernel - The Minimal Reality Ground

This module implements the foundational layer establishing that:
- No thinking without reality
- No trace without reality
- No learning without reality's resistance to hallucination
- Reality is the precondition for the system's possibility, not generated by it

Key Laws:
- Reality is not produced by the system
- Reality is the ground for all traces
- Observer is part of reality, not external to it
- Embodied human is the first reality (body, sensation, need, action)
- Reality has domains: Self, Life, World, Relational
- Reality status progression: Physical → Biological → Social → Conceptual → Symbolic → Hypothetical
- RealityEffect is what reality produces, not reality itself
- No mode transfer without bridge validation
- Reality cannot be CERTIFIED by the system (reality precedes certification)
- Hypothetical reality cannot produce physical effects without bridge

This is the absolute ground layer - Layer -2.
"""

from .reality_domain import RealityDomain, DomainType
from .reality_status import RealityStatus
from .minimal_reality_unit import MinimalRealityUnit
from .reality_effect import RealityEffect, EffectType
from .embodied_observer import EmbodiedObserver, BodyState, NeedState
from .life_context import LifeContext, LifePhase
from .world_context import WorldContext, WorldType
from .reality_bridge import RealityBridge, BridgeType, BridgeValidation
from .reality_validator import RealityValidator

__all__ = [
    "RealityDomain",
    "DomainType",
    "RealityStatus",
    "MinimalRealityUnit",
    "RealityEffect",
    "EffectType",
    "EmbodiedObserver",
    "BodyState",
    "NeedState",
    "LifeContext",
    "LifePhase",
    "WorldContext",
    "WorldType",
    "RealityBridge",
    "BridgeType",
    "BridgeValidation",
    "RealityValidator",
]
